In [1]:
# 수학 라이브러리
import numpy as np

# 데이터 라이브러리
import pandas as pd

# 차트 라이브러리
import matplotlib.pyplot as plt

# Data Load

In [2]:
# pandas의 read_csv를 이용하여 data를 로드함

# read_csv(file.csv): file.csv를 로드한 후, DataFrame(pandas에서 데이터를 저장하는 형식)을 반환함
dataset = pd.read_csv('Salary_Data.csv')
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

- X(YearsExperience, 경력)을 입력으로 하여 y(Salary, 연봉)을 예측하는 Linear regression model을 생성한다.

# 2. Dataset을 numpy의 ndarray 형태로 변경

In [6]:
print(type(dataset))

<class 'pandas.core.frame.DataFrame'>

- dataset은 DataFrame 타입으로 값(value)뿐만 아니라 column(열) 이름, 각 row(행) 이름 또는 index를 가지고 있다.
- 실제로 우리가 machine learning에서 활용할 경우, 각 값(value) 외에 column이나 row의 정보는 필요 없다.
- numpy의 ndarray는 value 정보만 가지고 있다.
- DataFrame.values는 DataFrame의 value만 가져오며, 타입이 ndarray이다.

In [5]:
# dataset의 column 목록
print(dataset.columns)

# column과 row를 제외한 dataset의 값만 ndarray로 반환함
print(dataset.values)

Index(['YearsExperience', 'Salary'], dtype='object')
[[1.10000e+00 3.93430e+04]
 [1.30000e+00 4.62050e+04]
 [1.50000e+00 3.77310e+04]
 [2.00000e+00 4.35250e+04]
 [2.20000e+00 3.98910e+04]
 [2.90000e+00 5.66420e+04]
 [3.00000e+00 6.01500e+04]
 [3.20000e+00 5.44450e+04]
 [3.20000e+00 6.44450e+04]
 [3.70000e+00 5.71890e+04]
 [3.90000e+00 6.32180e+04]
 [4.00000e+00 5.57940e+04]
 [4.00000e+00 5.69570e+04]
 [4.10000e+00 5.70810e+04]
 [4.50000e+00 6.11110e+04]
 [4.90000e+00 6.79380e+04]
 [5.10000e+00 6.60290e+04]
 [5.30000e+00 8.30880e+04]
 [5.90000e+00 8.13630e+04]
 [6.00000e+00 9.39400e+04]
 [6.80000e+00 9.17380e+04]
 [7.10000e+00 9.82730e+04]
 [7.90000e+00 1.01302e+05]
 [8.20000e+00 1.13812e+05]
 [8.70000e+00 1.09431e+05]
 [9.00000e+00 1.05582e+05]
 [9.50000e+00 1.16969e+05]
 [9.60000e+00 1.12635e+05]
 [1.03000e+01 1.22391e+05]
 [1.05000e+01 1.21872e+05]]

- 여기서 우리는 ndarray를 통해 model을 생성할 예정이므로 dataset.value를 이용한다.

In [9]:
# dataset DataFrame의 value만 가져와서 arr_data라는 ndarray에 저장함
arr_data = dataset.values

In [10]:
# ndarray.shape은 행과 열의 수를 반환함
print(arr_data.shape)

(30, 2)

- arr_data.shape은 (30, 2)이며, 30개의 행, 2개의 열로 구성되어 있다는 의미이다,

# 3. X와 y의 분리

- arr_data는 X와 y를 모두 포함하고 있다.
- arr_data에서 첫 번째 열(YearsExperience)은 X로, 두 번째 열(Salary)는 y로 사용한다.
- YearExperience로 Salary를 예측하는 linear regression model을 생성한다.

In [15]:
# indexing: index를 사용해서 특정 위치의 값을 가져옴
# arr_data의 4번째 행, 2번째 열의 값을 확인
# index는 항상 0부터 시작함
print(arr_data[3, 1])

43525.0

In [16]:
# slicing: index의 범위를 사용해서 특정 영역의 값을 가져옴
# X: arr_data의 전체 행, 첫 번째 열
# y: arr_data의 전체 행, 두 번째(마지막) 열
# 범위 표기 방법
# - a:b -> index a부터 index b-1까지 ex> 1:4 -> 1, 2, 3 index
# - a: -> index a부터 끝까지 ex> 1: -> 1부터 마지막 index까지 포함
# - :b -> 처음부터(index=0) index b-1까지 ex> :4 -> 0, 1, 2, 3
# - : -> (a와 b 모두 생략) 전체 index
X = arr_data[:, 0]
y = arr_data[:, 1]

In [20]:
# ndarray.shape을 했을 때, 반환하는 값의 수는 ndarray의 차원을 의미함
# ex> (30, 1): 2D array, (30,): 1D array, (1, 30): 2D array
print(X.shape, y.shape)

# arr_data[:, 0], arr_data[:, 1]로 ndarray를 slicing하면 1D array가 됨
# 그러나, sklearn package에서 X는 반드시 2D array만 허용됨(y는 1D array 가능)

(30,) (30,)

In [19]:
print(y)

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]

In [24]:
# 2D array data를 가정
# data[index, index] -> 0D array(스칼라)
# data[범위, index] or data[index, 범위]-> 1D array
# data[범위, 범위] -> 2D array
# -> dataset[범위, 범위]로 X를 추출함
X = arr_data[:, 0:1]

# 0:1은 index 0부터 index 1-1까지이므로 index 0만 해당됨
print(X.shape, arr_data[:, 0].shape)
print(X.ndim, arr_data[:, 0].ndim)
print(X)
print(arr_data[:, 0])

(30, 1) (30,)
2 1
[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]
[ 1.1  1.3  1.5  2.   2.2  2.9  3.   3.2  3.2  3.7  3.9  4.   4.   4.1
  4.5  4.9  5.1  5.3  5.9  6.   6.8  7.1  7.9  8.2  8.7  9.   9.5  9.6
 10.3 10.5]

In [25]:
# arr_data[:, 0:1]은 arr_data[:, :1]과 동일함
# ndarray에서 전체 크기와 관계 없이 마지막 index는 -1로 대체될 수 있음
# arr_data의 경우, 2개의 column으로 구성되어 있으므로,
# 1이 column에 대해 마지막 index이며, 이는 -1로 대체될 수 있음
# 그러므로 arr_data[:, 0:1] -> arr_data[:, :1] -> arr_data[:, :-1]은 모두 동일함

# ex> shape이 (100, 9)인 dataset의 X는 1번째 column부터 8번째 column까지에 해당한다면
# -> X = dataset[:, 0:8] -> X = dataset[:, :-1]
X = arr_data[:, :-1]
y = arr_data[:, -1]

# X는 반드시 2D array를 사용하고,
# y는 주로 1D array를 사용함
print(X.shape, y.shape)

(30, 1) (30,)

# 4. 학습/테스트 데이터 분리

- 학습 데이터란 학습에 사용되는 데이터를 의미하며, 테스트 데이터는 생성된 모델의 성능을 평가하기 위한 학습에 사용되지 않은 데이터이다.

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# train_test_split(data1, data2, test_size, random_state)
# data1, data2: 학습과 테스트로 분리할 데이터(data는 하나만 입력해도 무방함)
# test_sizez: 테스트로 사용할 데이터의 비율
# -> test_size=0.2: 전체 데이터에 대해 20%를 테스트에 사용
# random_state: train_test_split은 기본적으로 데이터를 shuffle한 후 추출하는데,
# 이때 random_state를 하나의 정수로 고정한 상태로 반복적으로 실행하면 항상 동일한 분리 결과가 나옴

# train_test_split(data1, data2, test_size, random_state)의 결과는
# data1의 학습데이터, data2의 학습데이터, data1의 테스트데이터, data2의 테스트데이터
# 순으로 반환됨(반드시 순서에 유의할 것)
print(X_test)

[[5.3]
 [7.1]
 [3.9]
 [6. ]
 [4.5]
 [6.8]]